apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uw3g95ajc-go 
  janus-idp.io/tekton: uw3g95ajc-go
  backstage.io/kubernetes-id: uw3g95ajc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uw3g95ajc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml