apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uw3g95ajc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uw3g95ajc-go 
  name: uw3g95ajc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uw3g95ajc-go 
